name: Compile template PDF

on:
  push:
    branches:
      - main

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    strategy:
      matrix:
        typst-version: ["0.11"]
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4

      - name: Setup typst
        uses: typst-community/setup-typst@v3
        with:
          typst-version: ${{ matrix.typst-version }}

      - name: Install TeX Gyre Font
        run:  sudo apt-get install -y tex-gyre

      - name: Compile PDF
        run: typst compile thesis.typ

      - name: Copy File
        run: |
          mkdir out
          cp ./thesis.pdf ./out/thesis.pdf

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'out'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
